---
title: "Vaccination Data"
author: "Megan Marziali"
date: "4/11/2021"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(readxl)

set.seed(100)
```

# Import data

Importing data and stripping vaccination numbers.

```{r message = FALSE, results = FALSE, warning = FALSE}
vacc.data = 
  read.csv("./data/owid-covid-data.csv", header = TRUE) %>% 
  janitor::clean_names() %>% 
  separate(
    date,
    sep = "-",
    into = c("year", "month", "day")
  ) %>% 
  select(
    "iso_code",
    "location",
    "year",
    "month",
    "day",
    "total_vaccinations"
  )

case.data = 
  read.csv("./data/owid-covid-data.csv", header = TRUE) %>% 
  janitor::clean_names() %>% 
  separate(
    date,
    sep = "-",
    into = c("year", "month", "day")
  ) %>% 
  select(
    "iso_code",
    "location",
    "year",
    "month",
    "day",
    "total_cases"
  )

test.data = 
  read.csv("./data/owid-covid-data.csv", header = TRUE) %>% 
  janitor::clean_names() %>% 
  separate(
    date,
    sep = "-",
    into = c("year", "month", "day")
  ) %>% 
  select(
    "iso_code",
    "location",
    "year",
    "month",
    "day",
    "total_tests"
  )
```

Selecting data within time period.

```{r}
vacc.rec = vacc.data %>% 
  filter(
    year == "2021",
    month == "03",
    day == "10"
  )

case.rec = case.data %>% 
  filter(
    year == "2021",
    month == "03",
    day == "10"
  )

test.rec = test.data %>% 
  filter(
    year == "2021",
    month == "03",
    day == "10"
  )
```

Export.

```{r}
write.csv(vacc.rec,"./data/vacc_03_2021.csv")

write.csv(case.rec,"./data/case_03_2021.csv")

write.csv(test.rec,"./data/test_03_2021.csv")
```


